# 模型配置
model:
  provider: "tongyi"  # openai/tongyi/doubao
  openai_model: "gpt-4-turbo"
  tongyi_model: "qwen-max"
  doubao_model: "doubao-1.6"
  
# 图片生成配置
image:
  engine: "tongyi"    # dalle/tongyi/volcengine
  style: "历史插画风格"  # 可自定义的图片风格
  
# 文章风格配置
style:
  article:
    tone: "生动有趣"  # 可选: 客观严谨/幽默讽刺/生动故事化
    length: 1000      # 文章长度
    examples:         # 参考文章示例
      - "在科技创新的浪潮中，马斯克如同一颗耀眼的星辰..."
      - "乔布斯的传奇人生：从车库创业到改变世界"
    structure:        # 文章结构要求
      sections: 4     # 章节数量
      section_length: "300字"  # 每章长度
  
# API密钥配置
api_keys:
  openai: "sk-..."  # OpenAI API密钥
  dashscope: "sk-..."  # 阿里云通义千问API密钥
  volc_access_key: "..."  # 火山引擎Access Key
  volc_secret_key: "..."  # 火山引擎Secret Key
  volc_region: "cn-beijing"  # 火山引擎区域

# 事实核查配置
verification:
  enabled: false  # 是否启用事实核查
